### PR TITLE
Change url to source code displayed in console

### PR DESCRIPTION
**Pull request by piotrzarzycki21**
- Change url to source code displayed in console
- Make small clean up ConsolePlugin class

### CODE REVIEW

**Comment by JoelProminic** [comment]
For the changed URL, I tested this by running the 'about' command on the console.  This looks fine:
    : Moonshine IDE 1.5.1
    : Source is under Apache License, Version 2.0
    : https://github.com/prominic/Moonshine-IDE
    : Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache 2), NativeApplicationUpdater (LGPL)
    : Running on Adobe AIR 22.0.0.153

However, the Help > About page looks like this after the update:
2017_09_21__about_page

Note that there is no space after "Build".  The build number format looks significantly different than for previous builds because we are using the Git revision number instead of the SVN revision number.

**Comment by piotrzarzycki21** [comment]
Hi @JoelProminic ,

Maybe in that case we should not display Build number ? What do you suggest ?

**Comment by JoelProminic** [comment]
@piotrzarzycki21 , I don't think we want to exclude the build number from the Moonshine code - we should be able to control it from the build tool.   We could use the Bamboo build number instead of the revision number, or pass a blank value (working with your code update above).  I'm favoring the former idea, currently.

**Comment by rat-moonshine** [comment]
Space now has been added before build value. 
image

**Comment by JoelProminic** [comment]
I updated the configuration to use the build number.    The number is noticeably low for now, but it should be easier to use than the Git revision number:
2017_09_22__moonshine_about_buildnumber

**Pull request merged**
